spring:
  application:
    name: demo
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

binance:
  btc:
    url: wss://stream.binance.com:9443/ws/btcusdt@trade
